# Generated by Django 3.0.5 on 2020-04-16 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.FileField(upload_to='arti_intelli/pic_names')),
                ('name', models.CharField(max_length=10)),
                ('stage', models.IntegerField()),
                ('classes', models.IntegerField()),
                ('birthday', models.DateField(default='1950-01-01')),
                ('student_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.FileField(upload_to='arti_intelli/pic_faces')),
                ('top', models.IntegerField()),
                ('bottom', models.IntegerField()),
                ('right', models.IntegerField()),
                ('left', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arti_intelli.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arti_intelli.Face')),
            ],
            bases=('arti_intelli.face',),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('in_time', models.TimeField(auto_now=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_left', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arti_intelli.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arti_intelli.Campus'),
        ),
    ]
