# Generated by Django 3.0.5 on 2020-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='in_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
