# Generated by Django 3.0.5 on 2020-04-16 07:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pic_name',
            field=imagekit.models.fields.ProcessedImageField(upload_to='arti_intelli/pic_names'),
        ),
        migrations.AlterField(
            model_name='face',
            name='pic_name',
            field=imagekit.models.fields.ProcessedImageField(upload_to='arti_intelli/pic_faces'),
        ),
    ]
