# Generated by Django 3.0.5 on 2020-04-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='out_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
