# Generated by Django 3.0.5 on 2020-04-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0002_auto_20200414_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
