# Generated by Django 3.0.5 on 2020-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0002_auto_20200416_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pic_name',
            field=models.FileField(upload_to='arti_intelli/pic_names'),
        ),
        migrations.AlterField(
            model_name='face',
            name='pic_name',
            field=models.FileField(upload_to='arti_intelli/pic_faces'),
        ),
    ]
