# Generated by Django 3.0.5 on 2020-04-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0003_auto_20200414_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
