# Generated by Django 3.0.5 on 2020-04-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti_intelli', '0004_auto_20200414_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
